@baseUrl = https://localhost:3443/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI5OUBleGFtcGxlLmNvbSIsInVzZXJJZCI6MTcsImlhdCI6MTc0Nzg2MDQ1MSwiZXhwIjoxNzQ3ODY0MDUxfQ.XUBYpTIH-qIAF2Mgo_VERJ4NMwQdimhz5Cu_3JKdiYk
### Solicitud para registrar usuario
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "user99@example.com",
    "passwordHash": "patata8889",
    "applicationId": 1
}

### Solicitud para autentificar usuario
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "user99@example.com",
    "passwordHash": "patata8889",
    "applicationId": 1
}

### Solicitud para autentificar usuario
POST {{baseUrl}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI5OUBleGFtcGxlLmNvbSIsInVzZXJJZCI6MTcsImlhdCI6MTc0Nzg2MDQ1MSwiZXhwIjoxNzQ3ODY0MDUxfQ.XUBYpTIH-qIAF2Mgo_VERJ4NMwQdimhz5Cu_3JKdiYk",
    "userId": 17
}